name: Trigger GitLab CI
on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call GitLab API
        run: |
          curl --request POST \
               --form token=noneed \
               --form ref=main \
               "${{ secrets.GITLAB_TRIGGER_TOKEN }}"
